### ISSUE TITLE
Templates in the same assembly as the application

### ISSUE THREAD

**Issue by Fido789** [soundaranbu/RazorTemplating#34]
Hello, 

Your library looks very promising, but I can not get it working with the templates in the same assembly (project) as the application. In the other words, I would like to have all files in one assembly. Is this possible?

**Comment by soundaranbu** [comment]
Hi @Fido789, Yes it's possible. But the project needs to target `Microsoft.NET.Sdk.Razor` so that it can compile the view files.
and have `AddRazorSupportForMvc` in the property group, similar to [this](https://github.com/soundaranbu/RazorTemplating/blob/master/examples/Templates/ExampleAppRazorTemplates/ExampleRazorTemplatesLibrary.csproj).

**Comment by Fido789** [comment]
Hello @soundaranbu , I finally managed to get it working and I must say so far I am very impressed. Everything works very well, just as you expect it to work, great library, thank you!

**Comment by soundaranbu** [comment]
Glad it worked! Thanks @Fido789
